# Generated by Django 5.2.14 on 2026-05-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("body", models.TextField()),
                ("starts_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Restrict to users in these groups. Leave empty to show to all users.",
                        related_name="admin_announcements",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin announcement",
                "verbose_name_plural": "Admin announcements",
                "ordering": ["-starts_at"],
            },
        ),
    ]
