# Generated by Django 5.2.14 on 2026-05-15 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_announcements", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminannouncement",
            options={
                "ordering": ["-starts_at"],
                "verbose_name": "admin announcement",
                "verbose_name_plural": "admin announcements",
            },
        ),
        migrations.AlterField(
            model_name="adminannouncement",
            name="body",
            field=models.TextField(verbose_name="body"),
        ),
        migrations.AlterField(
            model_name="adminannouncement",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="expires at"
            ),
        ),
        migrations.AlterField(
            model_name="adminannouncement",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Restrict to users in these groups. Leave empty to show to all users.",
                related_name="admin_announcements",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="adminannouncement",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="adminannouncement",
            name="starts_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="starts at"
            ),
        ),
        migrations.AlterField(
            model_name="adminannouncement",
            name="summary",
            field=models.TextField(verbose_name="summary"),
        ),
        migrations.AlterField(
            model_name="adminannouncement",
            name="title",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="adminannouncement",
            name="version",
            field=models.CharField(
                blank=True,
                help_text="Optional release version reference (e.g. 2.0.0)",
                max_length=50,
                verbose_name="version",
            ),
        ),
    ]
