# Generated by Django 5.2.14 on 2026-05-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_announcements", "0002_alter_adminannouncement_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminannouncement",
            name="summary",
            field=models.CharField(max_length=200, verbose_name="summary"),
        ),
    ]
