# Generated by Django 5.2.14 on 2026-05-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_announcements", "0003_alter_adminannouncement_summary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adminannouncement",
            old_name="is_active",
            new_name="is_published",
        ),
        migrations.AlterField(
            model_name="adminannouncement",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="published"),
        ),
    ]
